<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 9</b></center>    
<left><b><h3>Roll No. : 112 </b></left>  
<left><b><h3>Name : Pratik Soneji</b></left>   
<pre>    

### 1. Create a NumPy array of 10 student marks and display its `dtype`, `size`, `ndim`, `shape`, `itemsize`, and `nbytes`.

In [1]:
import numpy as np
arr1= np.array([2,3,4,5,6,7])
print(arr1)
print(arr1.dtype)
print(arr1.size)
print(arr1.ndim)
print(arr1.shape)
print(arr1.itemsize)

[2 3 4 5 6 7]
int64
6
1
(6,)
8


### 2.Create NumPy arrays using zeros, ones, full, arange, linspace, and identity functions.

In [2]:
import numpy as np

arr1 = np.zeros((3,4))
arr2 = np.ones((5,3))
arr3 = np.full((4,4),7)
arr4 = np.arange(2,20,2)
arr5 = np.linspace(1,50,5)
arr6 = np.identity(5)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[ 2  4  6  8 10 12 14 16 18]
[ 1.   13.25 25.5  37.75 50.  ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 3. Create an array of numbers from 1 to 25, reshape it into a 5×5 matrix, and display its transpose.

In [3]:
arr = np.arange(1,26).reshape((5,5)).transpose()
print(arr)

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


### 4. Generate marks of 20 students randomly between 0 and 100 and find their highest, lowest, and average marks.

In [4]:
marks = np.random.randint(0, 101, 20)
print("Marks of 20 student ")
print(marks)
print("Highest marks ", np.max(marks))
print("Lowest marks ", np.min(marks))
print("Average marks ", np.mean(marks))

Marks of 20 student 
[89  6 20 65 21 28 29 10  1 33 50  7 95 86 41 83 45 28 55 65]
Highest marks  95
Lowest marks  1
Average marks  42.85


### 5. Generate random numbers using `rand()`, `randn()`, `uniform()`, and `normal()`. Use a seed to reproduce the results.

In [5]:
np.random.randint(42)
print(np.random.rand(6))
print(np.random.randn(3))
print(np.random.uniform(1,9, 3))
print(np.random.normal(20, 3, 2))

[0.49217797 0.33977777 0.26804673 0.63736623 0.15399062 0.99552689]
[ 0.04981187 -0.13320092  1.52992557]
[4.7288624  5.40120903 6.41509457]
[23.55882566 16.88173368]


### 6. Given roll numbers 101–120, randomly select 5 students without replacement and demonstrate shuffling and permutation.

In [6]:

np.random.seed(10)

roll = np.arange(101, 121)

print(np.random.choice(roll, 5, replace=False))
print(np.random.permutation(roll))

shuffle = roll.copy()
np.random.shuffle(shuffle)
print(shuffle)

[108 111 106 107 104]
[103 101 110 111 116 114 108 117 119 113 106 107 104 118 115 105 109 102
 120 112]
[106 117 120 113 115 105 104 118 102 116 108 107 101 103 110 109 111 112
 114 119]


### 7. Given marks of 15 students, calculate sum, mean, median, minimum, maximum, variance, and standard deviation.

In [7]:
marks = np.array([44, 65, 29, 92, 76, 74, 61, 69, 35, 60, 80, 72, 81, 45, 50])
print("Marks:", marks)
print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Variance:", np.var(marks))
print("Standard Deviation:", np.std(marks))

Marks: [44 65 29 92 76 74 61 69 35 60 80 72 81 45 50]
Sum: 933
Mean: 62.2
Median: 65.0
Minimum: 29
Maximum: 92
Variance: 310.82666666666665
Standard Deviation: 17.630276987803303


### 8. Given daily sales for 10 days, calculate total sales, average sales, cumulative sales, and cumulative product.

In [8]:
sales = np.array([100, 150, 200, 120, 180, 250, 300, 220, 170, 210])

print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Cumulative Sales:", np.cumsum(sales))
print("Cumulative Product:", np.cumprod(sales))

Total Sales: 1900
Average Sales: 190.0
Cumulative Sales: [ 100  250  450  570  750 1000 1300 1520 1690 1900]
Cumulative Product: [                 100                15000              3000000
            360000000          64800000000       16200000000000
     4860000000000000  1069200000000000000 -2703440737095516160
  4126511494937706496]


### 9. Create two NumPy arrays and perform addition, subtraction, multiplication, division, floor division, modulus, and exponentiation.

In [9]:

a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 5, 8, 10])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Exponentiation:", a ** b)

Addition: [12 24 35 48 60]
Subtraction: [ 8 16 25 32 40]
Multiplication: [ 20  80 150 320 500]
Division: [5. 5. 6. 5. 5.]
Floor Division: [5 5 6 5 5]
Modulus: [0 0 0 0 0]
Exponentiation: [              100            160000          24300000     6553600000000
 97656250000000000]


### 10. Create an unsorted array of student marks and display it in ascending and descending order. Also find the sorted indices.

In [10]:

marks = np.array([75, 42, 89, 63, 95, 58])

print("Ascending:", np.sort(marks))
print("Descending:", np.sort(marks)[::-1])
print("Sorted Indices:", np.argsort(marks))

Ascending: [42 58 63 75 89 95]
Descending: [95 89 75 63 58 42]
Sorted Indices: [1 5 3 0 2 4]


### 11. Given the following NumPy array:
Write a program to display:

- First 5 elements
- Last 4 elements
- Elements from index 2 to 6
- Every alternate element

In [11]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("First 5:", arr[:5])
print("Last 4:", arr[-4:])
print("Index 2 to 6:", arr[2:7])
print("Alternate:", arr[::2])

First 5: [10 20 30 40 50]
Last 4: [ 70  80  90 100]
Index 2 to 6: [30 40 50 60 70]
Alternate: [10 30 50 70 90]


### 12. Given the following NumPy array:
Write a program to display:

- The array in reverse order
- Every second element in reverse order
- Last 5 elements in reverse order

In [12]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Reverse:", arr[::-1])
print("Every second reverse:", arr[::-2])
print("Last 5 reverse:", arr[-1:-6:-1])

Reverse: [100  90  80  70  60  50  40  30  20  10]
Every second reverse: [100  80  60  40  20]
Last 5 reverse: [100  90  80  70  60]


### 13. Given following NumPy Array:
Write a program to display:

- First two rows
- Last two rows
- Alternate rows
- Rows from index 1 to 3

In [13]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120],
                [130, 140, 150]])

print("First two rows:")
print(arr[:2])

print("Last two rows:")
print(arr[-2:])

print("Alternate rows:")
print(arr[::2])

print("Rows from index 1 to 3:")
print(arr[1:4])

First two rows:
[[10 20 30]
 [40 50 60]]
Last two rows:
[[100 110 120]
 [130 140 150]]
Alternate rows:
[[ 10  20  30]
 [ 70  80  90]
 [130 140 150]]
Rows from index 1 to 3:
[[ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


### 14. Given following NumPy Array:
Write a program to display:
- First two columns
- Last three columns
- First three rows and last two columns
- A 2×3 sub-array from the center

In [14]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150],
                [160, 170, 180, 190, 200]])

print("First two columns:")
print(arr[:, :2])

print("Last three columns:")
print(arr[:, -3:])

print("First three rows and last two columns:")
print(arr[:3, -2:])

print("2x3 sub-array from center:")
print(arr[1:3, 1:4])

First two columns:
[[ 10  20]
 [ 60  70]
 [110 120]
 [160 170]]
Last three columns:
[[ 30  40  50]
 [ 80  90 100]
 [130 140 150]
 [180 190 200]]
First three rows and last two columns:
[[ 40  50]
 [ 90 100]
 [140 150]]
2x3 sub-array from center:
[[ 70  80  90]
 [120 130 140]]


### 15. Given following NumPy Array:
Write a program to display:
- The matrix with rows in reverse order
- The matrix with columns in reverse order
- The matrix with both rows and columns reversed
- Alternate rows and alternate columns

In [15]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120],
                [130, 140, 150, 160]])

print("Rows reversed:")
print(arr[::-1])

print("Columns reversed:")
print(arr[:, ::-1])

print("Rows and columns reversed:")
print(arr[::-1, ::-1])

print("Alternate rows and columns:")
print(arr[::2, ::2])

Rows reversed:
[[130 140 150 160]
 [ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]
Columns reversed:
[[ 40  30  20  10]
 [ 80  70  60  50]
 [120 110 100  90]
 [160 150 140 130]]
Rows and columns reversed:
[[160 150 140 130]
 [120 110 100  90]
 [ 80  70  60  50]
 [ 40  30  20  10]]
Alternate rows and columns:
[[ 10  30]
 [ 90 110]]


### 15. Given an array of marks, write a program to display students who scored more than 75 marks.

In [16]:

marks = np.array([65, 80, 72, 90, 55, 85, 70, 95])

print(marks[marks > 75])

[80 90 85 95]


### 16. Given an array, write a program to display elements that are greater than 30 and less than 70.

In [17]:

arr = np.array([10, 25, 35, 45, 55, 65, 75, 85])

print(arr[(arr > 30) & (arr < 70)])

[35 45 55 65]


### 17. Given an array, write a program to display elements that are divisible by 5 and greater than 25, and then display elements that are either less than 20 or greater than 45.

In [18]:
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

print("Divisible by 5 and > 25:")
print(arr[(arr % 5 == 0) & (arr > 25)])

print("Less than 20 or greater than 45:")
print(arr[(arr < 20) | (arr > 45)])

Divisible by 5 and > 25:
[30 35 40 45 50 55]
Less than 20 or greater than 45:
[10 15 50 55]
